server:
  tomcat:
    uri-encoding: utf-8
  port: 80
  servlet:
    context-path: /XM06

## 数据源配置
spring:
  mvc:
    async:
      request-timeout: 60000
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClass: com.mysql.jdbc.Driver
    user: Administrator
    password: XWClassroom20202023
    jdbcUrl: jdbc:mysql://127.0.0.1:3366/yjykfsj2021?useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
  mail:
    host: smtp.qq.com
    username: 914577981@qq.com
    password: jwvgwxhhnhnhbdhe
    default-encoding: UTF-8


## mybatis的配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: org.xm06.pms.dao
  configuration:
    ## 下划线转驼峰
    map-underscore-to-camel-case: true

## 分页助手设置
pagehelper:
  helper-dialect: mysql

logging:
  file:
    name: D:/webapps/teach/yjykfsj2021/XM06_log/mapping.log


knife4j:
  enable: true